(venv) PS C:\Users\Lenovo\UIT\SkinSage> python app.py
Database URL: postgresql://postgres:Trang179%21@db.icvqowxrxnqgcceoxxob.supabase.co:5432/postgres
ðŸ”§ Configuring Flask application...
âœ… All required environment variables are set
Configuring for Supabase database...
âœ… Flask application configured successfully
Traceback (most recent call last):
  File "C:\Users\Lenovo\UIT\SkinSage\app.py", line 52, in <module>
    import models
  File "C:\Users\Lenovo\UIT\SkinSage\models.py", line 6, in <module>
    class User(UserMixin, db.Model):
  File "C:\Users\Lenovo\UIT\SkinSage\venv\Lib\site-packages\flask_sqlalchemy\model.py", line 100, in __init__
    super().__init__(name, bases, d, **kwargs)
  File "C:\Users\Lenovo\UIT\SkinSage\venv\Lib\site-packages\flask_sqlalchemy\model.py", line 120, in __init__
    super().__init__(name, bases, d, **kwargs)
  File "C:\Users\Lenovo\UIT\SkinSage\venv\Lib\site-packages\sqlalchemy\orm\decl_api.py", line 195, in __init__
    _as_declarative(reg, cls, dict_)
  File "C:\Users\Lenovo\UIT\SkinSage\venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 247, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\UIT\SkinSage\venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 328, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\UIT\SkinSage\venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 520, in __init__
    super().__init__(registry, cls_, mapper_kw)
  File "C:\Users\Lenovo\UIT\SkinSage\venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 344, in __init__
    instrumentation.register_class(
  File "C:\Users\Lenovo\UIT\SkinSage\venv\Lib\site-packages\sqlalchemy\orm\instrumentation.py", line 684, in register_class
    manager._update_state(
  File "C:\Users\Lenovo\UIT\SkinSage\venv\Lib\site-packages\sqlalchemy\orm\instrumentation.py", line 209, in _update_state
    registry._add_manager(self)
  File "C:\Users\Lenovo\UIT\SkinSage\venv\Lib\site-packages\sqlalchemy\orm\decl_api.py", line 1380, in _add_manager
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Class '<class 'models.User'>' already has a primary mapper defined.